#DEBUG 模式 (开发者选项)
DebugMode: false
#检查玩家装备时间 例如: 100 为 100tick 即 5s
CheckPlayerEquipTime: 100
StatsGuiName: "&a套装属性界面"
#套装Lore提示
SuitLore:
  #是否开启
  #注意 开启后再关闭将会对套装物品lore造成不可逆伤害
  enable: true
  #所在物品lore的部位 top 最顶端 bottom 最底部
  #举个例子比如lore列表是这样的
  #我是一条原本的lore
  #攻击加10
  #防御加20
  #
  #当设置为 top 时 如果是套装物品 lore 列表会被改变成这样
  #<XXX套装 手部 √>
  #<#XXX套装 头部 √>
  #<XXX套装 胸部 √>
  #<XXX套装 腿部 ×>
  #<XXX套装 脚部 √>
  #我是一条原本的lore
  #攻击加10
  #防御加20
  #
  #当设置为 bottom 时 如果是套装物品 lore 列表会被改变成这样
  #我是一条原本的lore
  #攻击加10
  #防御加20
  #<XXX套装 手部 √>
  #<XXX套装 头部 √>
  #<XXX套装 胸部 √>
  #<XXX套装 腿部 ×>
  #<XXX套装 脚部 √>
  location: 'top'
  loreFindTop: "&3-----套装-----"
  #套装部位lore格式
  loreFormat:
    '手部':
       have: '&a[<suitName> <suitPartName> √]'
       notHave: '&c[<suitName> <suitPartName> ×]'
    '头部':
       have: '&a[<suitName> <suitPartName> √]'
       notHave: '&c[<suitName> <suitPartName> ×]'
    '胸部':
       have: '&a[<suitName> <suitPartName> √]'
       notHave: '&c[<suitName> <suitPartName> ×]'
    '腿部':
       have: '&a[<suitName> <suitPartName> √]'
       notHave: '&c[<suitName> <suitPartName> ×]'
    '脚部':
       have: '&a[<suitName> <suitPartName> √]'
       notHave: '&c[<suitName> <suitPartName> ×]'