name: QiLingSuitPlugin
main: cc.canyi.qilingsuit.QiLingSuitPlugin
version: 1.0.4-BETA
softdepend: [BigAttribute, SX-Attribute, AttributePlus, PlaceholderAPI, DragonCore, ItemLoreOrigin]
author: CanYi
commands:
  qilingsuit: