name: QiLingSuitPlugin
main: cc.canyi.qilingsuit.QiLingSuitPlugin
version: 2.0.0-BETA
softdepend: [BigAttribute, SX-Attribute, AttributePlus, PlaceholderAPI, DragonCore, ItemLoreOrigin]
author: CanYi
commands:
  qilingsuit: